import type { Sample } from '../types/sample';

export const MOCK_SAMPLES: Sample[] = [
  {
    id: 'sample-react-spa',
    name: 'React SPA',
    framework: 'Web App (React)',
    description: 'Simple React Single Page Application',
    repoUrl: 'https://github.com/wso2/choreo-samples/tree/main/react-single-page-app',
    branch: 'main',
    componentDirectory: '/react-single-page-app',
    buildPreset: 'react',
    buildCommand: 'npm run build',
    buildPath: '/build',
    port: 8080,
  },
  {
    id: 'sample-vue-spa',
    name: 'Vue SPA',
    framework: 'Web App (Vue)',
    description: 'Simple Vue Single Page Application',
    repoUrl: 'https://github.com/wso2/choreo-samples/tree/main/vue-single-page-application',
    branch: 'main',
    componentDirectory: '/vue-single-page-application',
    buildPreset: 'vuejs',
    buildCommand: 'npm run build',
    buildPath: '/dist',
    port: 8080,
  },
  {
    id: 'sample-angular-spa',
    name: 'Angular SPA',
    framework: 'Web App (Angular)',
    description: 'Simple Angular Single Page Application',
    repoUrl: 'https://github.com/wso2/choreo-samples/tree/main/angular-single-page-app',
    branch: 'main',
    componentDirectory: '/angular-single-page-app',
    buildPreset: 'angular',
    buildCommand: 'npm run build',
    buildPath: '/dist',
    port: 8080,
  },
  {
    id: 'sample-hello-world-go',
    name: 'Hello World Go',
    framework: 'Web App (Go)',
    description: 'A Hello World web app in Go',
    repoUrl: 'https://github.com/wso2/choreo-samples/tree/main/hello-world-go-webapp',
    branch: 'main',
    componentDirectory: '/hello-world-go-webapp',
    buildPreset: 'go',
    buildCommand: 'go build -o app',
    buildPath: '/',
    port: 8080,
  },
];
